<a href="https://colab.research.google.com/github/klysman08/Data-science-e-Machine-Learning/blob/master/Day_4_Regress%C3%A3o.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Regressão

Técnica estatistica de modelagem que consiste no relacionamento entre variaveis dependentes e independentes. <br>
Muito ulitilazada para análises preditivas e de series temporais e para amostras ruidosas de dados.

É a utilização de uma reta que estima o melhor comportamento dos dados e minimiza o somatorio total dos erros de cada elemento sobre a reta.


In [0]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [45]:
df = pd.read_csv('https://s3.amazonaws.com/pycourse/50_Startups.csv')
df.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [0]:
#Extrair as matrizes X e y para regrassão do dataset

X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0) #random embaralha #stratify mantem proporcional a divisão das labels

In [0]:
#Normalizando os dados
from sklearn.preprocessing import StandardScaler

In [49]:
sc = StandardScaler()
X_train.shape

(40, 4)

In [50]:
X_train[:, :-1] = sc.fit_transform(X_train[:, :-1])  #Fit é somente para treino na base de dados de treino, aplica em todas as colunas exeto a ultima coluna que é uma str
X_test[:, :-1] = sc.transform(X_test[:, :-1]) # Aplica a formula nos dados
print(X_train[:5, :])

[[-0.3500645436227844 -0.7854710924793271 0.1011968019362538 'Florida']
 [-0.555303187426314 -1.481174262628151 0.02734979174277092 'New York']
 [0.07935762307586282 0.8013338146656704 -0.551521323997471 'Florida']
 [-0.5463823849331263 1.3250581707161837 0.07011683779235604 'California']
 [0.4348537132854595 -0.3559866348200946 0.7514851578736048 'Florida']]


In [0]:
#Tratamento de variaveis categoricas -one-hot-encoding

from sklearn.preprocessing import LabelEncoder, OneHotEncoder


In [52]:
le_X = LabelEncoder() #converte as coluna str dos paiseis em int
X_train[:, -1] = le_X.fit_transform(X_train[: ,-1])
X_test[:, -1] = le_X.fit_transform(X_test[: ,-1])
print(X_train[:5, :])

[[-0.3500645436227844 -0.7854710924793271 0.1011968019362538 1]
 [-0.555303187426314 -1.481174262628151 0.02734979174277092 2]
 [0.07935762307586282 0.8013338146656704 -0.551521323997471 1]
 [-0.5463823849331263 1.3250581707161837 0.07011683779235604 0]
 [0.4348537132854595 -0.3559866348200946 0.7514851578736048 1]]


In [53]:
#Aplicando o one-hote encoding

ohe = OneHotEncoder(categorical_features=[3])
X_train = ohe.fit_transform(X_train).toarray()
X_test = ohe.transform(X_test).toarray()

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [54]:
print(X_train[:5,:])

[[ 0.          1.          0.         -0.35006454 -0.78547109  0.1011968 ]
 [ 0.          0.          1.         -0.55530319 -1.48117426  0.02734979]
 [ 0.          1.          0.          0.07935762  0.80133381 -0.55152132]
 [ 1.          0.          0.         -0.54638238  1.32505817  0.07011684]
 [ 0.          1.          0.          0.43485371 -0.35598663  0.75148516]]


In [0]:
#evitando Dummy varible trap
X_train = X_train[:,1:]
X_test = X_test[:,1:]

In [58]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)
LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [0]:
y_pred = regressor.predict(X_test)

In [61]:
#calculo rmse

rmse = np.sqrt(np.mean((y_test - y_pred)**2))
print(rmse)

9137.990152794953
