<a href="https://colab.research.google.com/github/klysman08/Machine-Learning/blob/master/Introduction_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Tutorial.

## Importing numpy.

In [0]:
import numpy as np

## Creating an ndarray from a list.

In [0]:
a = np.array([4, 3, 2, 1], dtype=np.int)

print(a)

[4 3 2 1]


## ndarray properties.

In [0]:
print(a)
print('a.ndim: ' + str(a.ndim))
print('a.shape: ' + str(a.shape))
print('a.dtype: ' + str(a.dtype))
print('a.size: ' + str(a.size))
print('type(a): ' + str(type(a)))

[4 3 2 1]
a.ndim: 1
a.shape: (4,)
a.dtype: int64
a.size: 4
type(a): <type 'numpy.ndarray'>


## Ascending numbers.

In [0]:
a = np.arange(50)
b = np.arange(20, 100, 10)

print(a)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
[20 30 40 50 60 70 80 90]


## Reshape.

In [0]:
a = np.arange(50)
a = a.reshape(5, 10)
b = a.ravel()

print(a)
print(b)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


## Numerical Operations.

In [0]:
b = np.arange(50) * 2
b = b.reshape(5, 10)

c = a + b

print(a)
print(b)
print(c)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
[[ 0  2  4  6  8 10 12 14 16 18]
 [20 22 24 26 28 30 32 34 36 38]
 [40 42 44 46 48 50 52 54 56 58]
 [60 62 64 66 68 70 72 74 76 78]
 [80 82 84 86 88 90 92 94 96 98]]
[[  0   3   6   9  12  15  18  21  24  27]
 [ 30  33  36  39  42  45  48  51  54  57]
 [ 60  63  66  69  72  75  78  81  84  87]
 [ 90  93  96  99 102 105 108 111 114 117]
 [120 123 126 129 132 135 138 141 144 147]]


In [0]:
b = (np.arange(50, dtype=np.float) + 1) * 2
b = b.reshape(5, 10)

c = b / (a + 1)

print(a)
print(b)
print(c)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
[[  2.   4.   6.   8.  10.  12.  14.  16.  18.  20.]
 [ 22.  24.  26.  28.  30.  32.  34.  36.  38.  40.]
 [ 42.  44.  46.  48.  50.  52.  54.  56.  58.  60.]
 [ 62.  64.  66.  68.  70.  72.  74.  76.  78.  80.]
 [ 82.  84.  86.  88.  90.  92.  94.  96.  98. 100.]]
[[2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]]


## Indexing.

In [0]:
a = a.reshape(5, 10)

b = a[0:2, 0:2]
c = a[1:4, 2:8]

print(a)
print(b)
print(c)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
[[ 0  1]
 [10 11]]
[[12 13 14 15 16 17]
 [22 23 24 25 26 27]
 [32 33 34 35 36 37]]


## Array of Zeros or Ones.

In [0]:
ones = np.ones((2, 3, 3))
zeros = np.zeros((2, 3, 3))

print(ones)
print(zeros)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


## Linear Spaces.

In [0]:
ls = np.linspace(0, 2, 10)

print(ls)

[0.         0.22222222 0.44444444 0.66666667 0.88888889 1.11111111
 1.33333333 1.55555556 1.77777778 2.        ]


## Random numbers.

In [0]:
integer = np.random.randint(0, 5)
uniform = np.random.random((5, 5))
normal = np.random.randn(5, 5)

print(integer)
print(uniform)
print(normal)

3
[[0.25417115 0.9563316  0.59273709 0.50647984 0.68746201]
 [0.18361068 0.3426837  0.66019849 0.90492182 0.5379276 ]
 [0.30451523 0.59043437 0.08731383 0.20010446 0.97497534]
 [0.22584421 0.89533297 0.1877737  0.70445073 0.18497326]
 [0.95753614 0.10527721 0.20217178 0.40393133 0.59374149]]
[[ 0.73792513  0.44866067 -0.81261535  0.27769866 -1.30845964]
 [ 0.32030549 -0.385629    0.18495295 -1.41361449  0.39078949]
 [ 0.23671481  1.0411309   0.58821633  0.01557563  0.22637883]
 [ 0.27128109 -1.13219193 -1.5553568  -0.17945856 -0.93218447]
 [-0.25776496  0.50027233 -1.96188735  0.58853199 -0.04714048]]


## Comparisons.

In [0]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[0, 2, 0], [4, 0, 6]])

arr3 = arr1 == arr2
arr4 = arr1 != arr2
arr5 = arr1 > arr2
arr6 = arr1 < 2

print(arr1)
print(arr2)
print(arr3)
print(arr4)
print(arr5)
print(arr6)

[[1 2 3]
 [4 5 6]]
[[0 2 0]
 [4 0 6]]
[[False  True False]
 [ True False  True]]
[[ True False  True]
 [False  True False]]
[[ True False  True]
 [False  True False]]
[[ True False False]
 [False False False]]


## Aggregate Functions.

In [0]:
a = np.arange(50, dtype=np.float).reshape(5, 10)

print(a)
print('sum ', a.sum())
print('min ', a.min())
print('max ', b.max(axis=0))
print('mean ', a.mean())
print('std ', np.std(a))
print('cumsum ', a.cumsum(axis=1))
print('median ', np.median(a))

[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]
 [20. 21. 22. 23. 24. 25. 26. 27. 28. 29.]
 [30. 31. 32. 33. 34. 35. 36. 37. 38. 39.]
 [40. 41. 42. 43. 44. 45. 46. 47. 48. 49.]]
('sum ', 1225.0)
('min ', 0.0)
('max ', 49)
('mean ', 24.5)
('std ', 14.430869689661812)
('cumsum ', array([[  0.,   1.,   3.,   6.,  10.,  15.,  21.,  28.,  36.,  45.],
       [ 10.,  21.,  33.,  46.,  60.,  75.,  91., 108., 126., 145.],
       [ 20.,  41.,  63.,  86., 110., 135., 161., 188., 216., 245.],
       [ 30.,  61.,  93., 126., 160., 195., 231., 268., 306., 345.],
       [ 40.,  81., 123., 166., 210., 255., 301., 348., 396., 445.]]))
('median ', 24.5)


## Sorting.

In [0]:
r = np.random.random((5, 5))

print(r)
print('sort ', np.sort(r))
print('sort ax 0 ', np.sort(r, axis=0))
print('sort ax 1 ', np.sort(r, axis=1))

[[0.96758249 0.41864355 0.79995135 0.12010576 0.5855505 ]
 [0.98995955 0.88413897 0.69432164 0.26363094 0.35278435]
 [0.35449633 0.69880211 0.63562218 0.92731165 0.86688729]
 [0.67355095 0.35987505 0.98642348 0.23648007 0.7267926 ]
 [0.48102544 0.1521885  0.6752884  0.30132769 0.02377827]]
('sort ', array([[0.12010576, 0.41864355, 0.5855505 , 0.79995135, 0.96758249],
       [0.26363094, 0.35278435, 0.69432164, 0.88413897, 0.98995955],
       [0.35449633, 0.63562218, 0.69880211, 0.86688729, 0.92731165],
       [0.23648007, 0.35987505, 0.67355095, 0.7267926 , 0.98642348],
       [0.02377827, 0.1521885 , 0.30132769, 0.48102544, 0.6752884 ]]))
('sort ax 0 ', array([[0.35449633, 0.1521885 , 0.63562218, 0.12010576, 0.02377827],
       [0.48102544, 0.35987505, 0.6752884 , 0.23648007, 0.35278435],
       [0.67355095, 0.41864355, 0.69432164, 0.26363094, 0.5855505 ],
       [0.96758249, 0.69880211, 0.79995135, 0.30132769, 0.7267926 ],
       [0.98995955, 0.88413897, 0.98642348, 0.92731165, 0.866

## Boolean Indexing.

In [0]:
a = np.arange(50, dtype=np.float).reshape(5, 10)
print(a)

a[a > 20] = -1
print(a)

a[a == 15] = -1000
print(a)

[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]
 [20. 21. 22. 23. 24. 25. 26. 27. 28. 29.]
 [30. 31. 32. 33. 34. 35. 36. 37. 38. 39.]
 [40. 41. 42. 43. 44. 45. 46. 47. 48. 49.]]
[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]
 [20. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]]
[[    0.     1.     2.     3.     4.     5.     6.     7.     8.     9.]
 [   10.    11.    12.    13.    14. -1000.    16.    17.    18.    19.]
 [   20.    -1.    -1.    -1.    -1.    -1.    -1.    -1.    -1.    -1.]
 [   -1.    -1.    -1.    -1.    -1.    -1.    -1.    -1.    -1.    -1.]
 [   -1.    -1.    -1.    -1.    -1.    -1.    -1.    -1.    -1.    -1.]]
