## O NumPy é uma poderosa biblioteca Python que é usada principalmente para realizar cálculos em Arrays Multidimensionais. O NumPy fornece um grande conjunto de funções e operações de biblioteca que ajudam os programadores a executar facilmente cálculos numéricos.

In [0]:
import numpy as np

In [18]:
a = np.array([1,2,3,4,5,])
#Cria um array a partir de uma lista

mat = np.array([[2,2],[8,3]])
mat
#Cria uma matriz 

mat[:][1]
#Acesar o elemento de nxn

array([8, 3])

In [19]:
mat.transpose() 
#Imprime a transposta da matriz. mat.T() também funciona

array([[2, 8],
       [2, 3]])

In [20]:
mat.sum()
#Soma os elementos do array

15

In [23]:
mat.argmax()
#mat.argmin()
#Obtem o maior valor e menor valor do array

2

In [30]:
lista = np.arange(1, 10000)
lista
#Cria um array de 0 a 10000 pulando de 1 em 1

array([   1,    2,    3, ..., 9997, 9998, 9999])

In [0]:
lista = lista[::500]
#Fatiamento de array. Vai do primeiro ao ultimo elemento da lista pulando de 500 em 500

In [0]:
lista2 = lista.copy()
#Copia os elementos da lista1 para a lista2

In [43]:
lista2.shape()

TypeError: ignored